#!/bin/bash

# Current working directory
CWD=$(pwd)

# Working directory
BASE_DIR="/tmp/raspberrypi"

# Create the initial image file (700MB)
dd if=/dev/zero of=$BASE_DIR/raspberry-manager.img bs=512 count=1400000

# Create the partition and set it bootable
fdisk $BASE_DIR/raspberry-manager.img <<EOF
n
p
1


a
w
EOF

partition_start=$(fdisk -l $BASE_DIR/raspberry-manager.img | awk '/^Device/{p=1;next}; p{gsub(/[^[:digit:]]/, "", $2); print $3}')
partition_end=$(fdisk -l $BASE_DIR/raspberry-manager.img | awk '/^Device/{p=1;next}; p{gsub(/[^[:digit:]]/, "", $2); print $4}')

losetup_start=$(( $partition_start * 512 ))
losetup_sizelimit=$(( $partition_end * 512 ))


#
echo "losetup -o $losetup_start --sizelimit $losetup_sizelimit /dev/loop1 $BASE_DIR/raspberry-manager.img"
