#!/bin/bash

# Install applications we need to build the environment.
apt-get --yes install debootstrap syslinux isolinux squashfs-tools genisoimage xorriso memtest86+ rsync wget ca-certificates

#----------------------------------------------------------#
#                      Configuration                       #
#----------------------------------------------------------#
# Defaults
BASE_DIR="/usr/share/raspbian-live"
LIVE_ARCH="i386"
LIVE_DISTRO="jessie"
KERNEL_VERSION="3.16.0-4-586"

# Load configuration
if [ -f /etc/raspbian-live ]; then
    # Base directory
    config_var=$(awk '/BASE_DIR=/' /etc/raspbian-live | sed 's/BASE_DIR=//' )
    if [ -n "$config_var" ];then
        BASE_DIR="$config_var"
    fi
    
    # Architecture
    config_var=$(awk '/ARCH=/' /etc/raspbian-live | sed 's/ARCH=//' )
    if [ -n "$config_var" ];then
        LIVE_ARCH="$config_var"
    fi

    # Distro
    config_var=$(awk '/DISTRO=/' /etc/raspbian-live | sed 's/DISTRO=//' )
    if [ -n "$config_var" ];then
        LIVE_DISTRO="$config_var"
    fi
    
    # Kernel version
    config_var=$(awk '/KERNEL=/' /etc/raspbian-live | sed 's/KERNEL=//' )
    if [ -n "$config_var" ];then
        KERNEL_VERSION="$config_var"
    fi
fi

#----------------------------------------------------------#
#                    Base environment                      #
#----------------------------------------------------------#
# Remove the chroot if it already exists
if [ -d $BASE_DIR/chroot ]; then
    rm -rf $BASE_DIR/chroot
fi

# Setup the base Debian environment
debootstrap --arch=$LIVE_ARCH --variant=minbase $LIVE_DISTRO $BASE_DIR/chroot http://ftp.us.debian.org/debian/

# A couple of important steps before we chroot
mount -o bind /dev $BASE_DIR/chroot/dev
cp /etc/resolv.conf $BASE_DIR/chroot/etc/resolv.conf

#----------------------------------------------------------#
#                 Read/Write Filesystem                    #
#----------------------------------------------------------#
if [ -f $BASE_DIR/raspberrypi-fs ]; then
    rm -f $BASE_DIR/raspberrypi-fs
fi

dd if=/dev/zero of=$BASE_DIR/raspberrypi-fs bs=600MB count=1
mkfs.vfat -F 32 $BASE_DIR/raspberrypi-fs

if [ ! -d $BASE_DIR/chroot/usr/share/raspberrypi ]; then
    mkdir -p $BASE_DIR/chroot/usr/share/raspberrypi
fi

mount $BASE_DIR/raspberrypi-fs $BASE_DIR/chroot/usr/share/raspberrypi

#----------------------------------------------------------#
#               Build the chroot installer                 #
#----------------------------------------------------------#
if [ -f $BASE_DIR/chroot/root/installer-chroot ]; then
    rm $BASE_DIR/chroot/root/installer-chroot
fi

wget https://raw.githubusercontent.com/JPG-Consulting/PiManagerLive/development/installer-chroot -O $BASE_DIR/chroot/root/installer-chroot
chown root:root $BASE_DIR/chroot/root/installer-chroot
chmod +x $BASE_DIR/chroot/root/installer-chroot

sed -i -E 's/^KERNEL_VERSION=.+/KERNEL_VERSION="$KERNEL_VERSION"/' $BASE_DIR/chroot/root/installer-chroot

#----------------------------------------------------------#
#                         Chroot                           #
#----------------------------------------------------------#
# Chroot to our Debian environment and install
chroot $BASE_DIR/chroot /bin/bash -x <<'EOF'
mount none -t proc /proc
mount none -t sysfs /sys
mount none -t devpts /dev/pts
export HOME=/root
export LC_ALL=C
apt-get update
apt-get install dialog dbus --yes --force-yes
dbus-uuidgen > /var/lib/dbus/machine-id

# Call the downloaded installer
/root/installer-chroot

# Clean up our Debian environment before leaving.
rm -f /var/lib/dbus/machine-id
apt-get clean
rm -rf /tmp/*
umount -lf /proc
umount -lf /sys
umount -lf /dev/pts
exit
EOF

#----------------------------------------------------------#
#                        Clean up                          #
#----------------------------------------------------------#
# Unmount dev from the chroot
umount -lf $BASE_DIR/chroot/dev
rm $BASE_DIR/chroot/etc/resolv.conf

# Unmount the read/write filesystem
umount $BASE_DIR/chroot/usr/share/raspberrypi

rm $BASE_DIR/chroot/root/installer-chroot

