#!/bin/bash

# Current working directory
CWD=$(pwd)

# Create the initial image file (700MB)
if [ -f /tmp/raspberry-manager.img ]; then
  rm /tmp/raspberry-manager.img
fi

dd if=/dev/zero of=/tmp/raspberry-manager.img bs=512 count=1400000

# Create the partition and set it bootable
fdisk /tmp/raspberry-manager.img <<EOF
n
p
1


a
w
EOF

partition_start=$(fdisk -l /tmp/raspberry-manager.img | awk '/^Device/{p=1;next}; p{gsub(/[^[:digit:]]/, "", $2); print $3}')
partition_end=$(fdisk -l /tmp/raspberry-manager.img | awk '/^Device/{p=1;next}; p{gsub(/[^[:digit:]]/, "", $2); print $4}')

losetup_start=$(( $partition_start * 512 ))
losetup_sizelimit=$(( $partition_end * 512 ))


# Add partition to loopback driver
losetup -o $losetup_start --sizelimit $losetup_sizelimit /dev/loop1 /tmp/raspberry-manager.img

# Format the partition
mkfs.ext4 /dev/loop1

# Mount the partition
if [ ! -d /mnt/liveusb ]; then
  mkdir /mnt/liveusb
fi

mount /dev/loop1 /mnt/liveusb

# Cleanup
# Unmount
umount /mnt/liveusb
# Delete loop device
losetup -l /dev/loop1

mv /tmp/raspberry-manager.img $CWD
